title: Volunteerism
tagline: Connecting Volunteers Together
description: >-
  Volunteerism allows you to find relevant volunteering opportunities near you and showcase the work that you’ve done.
logo: "/assets/img/logo.png"

plugins:
  - jekyll-seo-tag